---
title: Намалюй обличчя
hero_image: images/banner.png
description: Придумай та намалюй обличчя або маску за допомогою геометричних фігур
meta_title: Проєкти з кодування для дітей і підлітків | Намалюй обличчя
meta_description: Вивчай Python за допомогою проєктів програмування Raspberry Pi Foundation для дітей і підлітків. За допомогою Python намалюй обличчя або маску, використовуючи геометричні фігури.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Що ти зробиш
  - title: Вибери тло
    completion:
      - engaged
  - title: Кола й еліпси
  - title: Прямокутники
  - title: Трикутники
  - title: Накладання фігур
  - title: Створи своє обличчя
    completion:
      - internal
  - title: Швидкий тест
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Додаткове завдання
    challenge: true
  - title: Що робити далі?
