---
title: Maak een gezicht
hero_image: images/banner.png
description: Ontwerp en teken een gezicht of masker met behulp van geometrische vormen
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Inleiding
  - 
    title: Kies een thema
  - 
    title: Vorm van het gezicht
    completion:
      - engaged
  - 
    title: Voeg ogen toe
  - 
    title: Voeg een mond toe
  - 
    title: Voeg meer details toe
    completion:
      - internal
  - 
    title: Reflectie
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Deel je project
  - 
    title: Wat kun je verder nog doen?
