title: Make a face
hero_image: images/banner.png
description: Design and draw a face or mask using geometric shapes 
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Choose a theme
  - title: Face shape
  - title: Add eyes
  - title: Add a mouth
  - title: Add more details
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: Share
  - title: What next?
