---
title: Tynnu wyneb
hero_image: images/banner.png
description: Dyluniwch a llunio wyneb neu fasg gan ddefnyddio siapiau geometrig
meta_title: Python coding projects for kids and teens | Make a face
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Write Python code to draw a face or mask using geometric shapes.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Cyflwyniad
  - 
    title: Dewis thema
  - 
    title: Siâp y wyneb
    completion:
      - engaged
  - 
    title: Ychwanegu llygaid
  - 
    title: Ychwanegu ceg
  - 
    title: Ychwanegu mwy o fanylion
    completion:
      - internal
  - 
    title: Myfyrio
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Uwchraddio dy brosiect
  - 
    title: Rhannu
  - 
    title: Beth nesaf?
