---
title: Ein Gesicht machen
hero_image: images/banner.png
description: Entwerfe und zeichne ein Gesicht oder eine Maske mit geometrischen Formen
meta_title: Python Programmierprojekte für Kinder und Jugendliche | Ein Gesicht machen
meta_description: Lerne Python mit den Programmierprojekten der Raspberry Pi Foundation für Kinder und Jugendliche. Schreibe Code in Python um ein Gesicht oder eine Maske mit geometrischen Formen zu zeichnen.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: Choose a theme
  - 
    title: Face shape
    completion:
      - engaged
  - 
    title: Add eyes
  - 
    title: Add a mouth
  - 
    title: Add more details
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: What next?
