---
title: Zeichne ein Gesicht
hero_image: images/banner.png
description: Entwerfe und zeichne ein Gesicht oder eine Maske mit geometrischen Formen
meta_title: Python Programmierprojekte für Kinder und Jugendliche | Zeichne ein Gesicht
meta_description: Lerne Python mit den Programmierprojekten der Raspberry Pi Foundation für Kinder und Jugendliche. Schreibe Code in Python um ein Gesicht oder eine Maske mit geometrischen Formen zu zeichnen.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: Das wirst du machen
  - title: Wähle einen Hintergrund
    completion:
      - engaged
  - title: Kreise und Ovale
  - title: Rechtecke
  - title: Dreiecke
  - title: Überlappende Formen
  - title: Erstelle dein Gesicht
    completion:
      - internal
  - title: Kurzes Quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Challenge
    challenge: true