---
title: Crie um rosto
hero_image: images/banner.png
description: Projete e desenhe um rosto ou máscara usando formas geométricas
meta_title: Projetos de programação Python para crianças e adolescentes | Crie um rosto
meta_description: Aprenda Python com os projetos de programação da Raspberry Pi Foundation para crianças e adolescentes. Escreva um código Python para desenhar um rosto ou máscara usando formas geométricas.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: What you will make
  - 
    title: Choose a background
    completion:
      - engaged
  - 
    title: Circles and ovals
  - 
    title: Rectangles
  - 
    title: Triangles
  - 
    title: Overlap shapes
  - 
    title: Create your face
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
