---
title: Crie um rosto
hero_image: images/banner.png
description: Projete e desenhe um rosto ou máscara usando formas geométricas
meta_title: Projetos de programação Python para crianças e adolescentes | Crie um rosto
meta_description: Aprenda Python com os projetos de programação da Raspberry Pi Foundation para crianças e adolescentes. Escreva um código Python para desenhar um rosto ou máscara usando formas geométricas.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Você vai fazer
  - 
    title: Escolha um tema
  - 
    title: Formato do rosto
    completion:
      - engaged
  - 
    title: Adicione olhos
  - 
    title: Adicione uma boca
  - 
    title: Adicione mais detalhes
    completion:
      - internal
  - 
    title: Teste rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Melhore o seu projeto
  - 
    title: Compartilhar
  - 
    title: O que vem depois?
