---
title: Haz una cara
hero_image: images/banner.png
description: Diseña y dibuja una cara o máscara usando formas geométricas
version: 4
listed: true
copyedit: true
last_tested: '2021-10-06'
steps:
  - title: Introducción
  - title: Elige un tema
  - title: Forma de la cara
    completion:
      - engaged
  - title: Agrega los ojos
  - title: Agrega una boca
  - title: Agrega más detalles
    completion:
      - internal
  - title: Reflexión
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Mejora tu proyecto
  - title: Comparte