---
title: Haz una cara
hero_image: images/banner.png
description: Diseña y dibuja una cara o máscara usando formas geométricas
meta_title: Python coding projects for kids and teens | Make a face
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Write Python code to draw a face or mask using geometric shapes.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Lo que harás
  - 
    title: Elige un tema
  - 
    title: Forma de la cara
    completion:
      - engaged
  - 
    title: Agrega los ojos
  - 
    title: Agrega una boca
  - 
    title: Agrega más detalles
    completion:
      - internal
  - 
    title: Examen rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: Comparte
  - 
    title: '¿Qué sigue?'
