---
title: Make a face
hero_image: images/banner.png
description: Design and draw a face or mask using geometric shapes
meta_title: Python coding projects for kids and teens | Make a face
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Write Python code to draw a face or mask using geometric shapes.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: You will make
  - 
    title: Choose a theme
  - 
    title: Face shape
    completion:
      - engaged
  - 
    title: Add eyes
  - 
    title: Add a mouth
  - 
    title: Add more details
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Ulepsz swój projekt
  - 
    title: Udostępnij
  - 
    title: Co dalej?
