---
title: Stwórz twarz
hero_image: images/banner.png
description: Zaprojektuj i narysuj twarz lub maskę używając kształtów geometrycznych
meta_title: Projekty programistyczne w Pythonie dla dzieci i młodzieży | Zbuduj twarz
meta_description: Naucz się języka Python z projektami programistycznymi Fundacji Raspberry Pi dla dzieci i młodzieży. Napisz kod Python, aby narysować twarz lub maskę za pomocą kształtów geometrycznych.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Zrobisz to
  - 
    title: Wybierz motyw
  - 
    title: Kształt ściany
    completion:
      - engaged
  - 
    title: Dodaj oczy
  - 
    title: Dodaj usta
  - 
    title: Dodaj więcej szczegółów
    completion:
      - internal
  - 
    title: Szybki quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Ulepsz swój projekt
  - 
    title: Udostępnij
  - 
    title: Co dalej?
