---
title: Faire un visage
hero_image: images/banner.png
description: Conçois et dessine un visage ou un masque à l'aide de formes géométriques
meta_title: Projets de codage Python pour enfants et adolescents | Faire un visage
meta_description: Apprends Python avec les projets de codage de la Raspberry Pi Foundation pour les enfants et les adolescents. Écris du code Python pour dessiner un visage ou un masque à l'aide de formes géométriques.
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Choisir un arrière-plan
    completion:
      - engaged
  - 
    title: Cercles et ovales
  - 
    title: Rectangles
  - 
    title: Triangles
  - 
    title: Formes superposées
  - 
    title: Créer ton visage
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Défi
    challenge: true
